In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv('C:/Users/user/Desktop/creditcard.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [5]:
# dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26       284807 non-null float64
V27       284807 non-null float64
V28       284807 non-null float64
Amount    284807 non-null float64
Class     284807 non-null int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [8]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [9]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [10]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [12]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [13]:
legit_sample = legit.sample(n=492)

In [14]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [15]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
214498,139697.0,1.192033,-2.645513,-1.368246,-0.359878,-1.341884,-0.116380,-0.284399,-0.211947,0.192514,...,0.707664,1.066778,-0.436039,0.769297,-0.030186,0.024106,-0.093899,0.038912,525.00,0
46824,42945.0,1.201245,-0.599558,0.604505,-0.807314,-0.434032,0.823050,-0.858524,0.365723,-0.860695,...,0.046794,0.191504,0.299998,-0.639175,-0.112026,-0.372801,0.085434,0.011683,6.41,0
85248,60675.0,-3.006429,-0.815538,1.462037,1.113696,0.085126,1.084880,-0.654740,-0.808509,-0.881555,...,0.162701,-0.143771,0.329086,-0.254146,0.279256,-0.006137,-0.493973,0.533954,57.50,0
95664,65412.0,-1.706828,1.216243,0.114310,1.084035,-0.653121,-0.559664,0.911122,0.615821,-1.182436,...,-0.125048,-0.442742,0.474038,0.364532,-0.270391,-0.623670,0.166097,-0.121757,141.00,0
14540,25742.0,0.130929,0.475437,0.921391,1.075616,0.097935,-0.464541,0.435428,0.054402,0.094119,...,0.024123,0.220836,0.130776,0.393479,-0.281325,-0.473685,0.012610,-0.063104,16.73,0

In [16]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [17]:
new_dataset['Class'].value_counts()

1    492
0    492
Name: Class, dtype: int64

In [18]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95863.268293,0.010963,-0.056167,-0.117719,-0.077433,0.100879,-0.083543,0.031180,0.052873,0.012667,...,0.033350,0.005625,0.015021,-0.017032,-0.037788,0.030074,-0.059315,-0.011134,-0.006862,90.226179
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [19]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [20]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
214498  139697.0  1.192033 -2.645513 -1.368246 -0.359878 -1.341884 -0.116380
46824    42945.0  1.201245 -0.599558  0.604505 -0.807314 -0.434032  0.823050
85248    60675.0 -3.006429 -0.815538  1.462037  1.113696  0.085126  1.084880
95664    65412.0 -1.706828  1.216243  0.114310  1.084035 -0.653121 -0.559664
14540    25742.0  0.130929  0.475437  0.921391  1.075616  0.097935 -0.464541
75526    56105.0  1.198520  0.290869  0.406668  0.627775 -0.434840 -0.870457
20983    31392.0  1.218765  0.396819  0.536853  0.814692 -0.595712 -1.368102
158892  111926.0  1.377175 -1.097077 -2.806054  0.868219  0.178415 -1.728746
98978    66904.0  1.337380  0.266593 -0.394412  0.169809  0.536488  0.242319
210777  138119.0  2.225286 -0.858085 -1.133630 -0.927493 -0.608179 -0.603939
158808  111783.0  1.977685 -0.154504 -1.683858 -0.058702  0.981265  0.721926
243432  151932.0  1.750049  1.014592 -1.707631  4.032913  1.508601  0.696983
94620    64956.0 -0.591020 -0.102077 -0.506572 -2.751057  1.442670  3.177189
66036    51852.0 -1.096867 -0.822421 -0.384113 -1.854383 -1.704296  0.122444
236183  148701.0 -2.294590 -2.566528 -1.842355 -4.294888  1.672855 -0.196827
157613  110133.0  1.962047  0.459489 -1.420699  1.521355  0.623170 -0.556809
243230  151849.0 -0.027176  1.013512 -2.344699 -0.430709  0.921411 -1.362416
30246    35838.0 -1.195375 -0.007929  0.696647 -1.403109  0.899893  4.803624
236619  148886.0  1.909959 -1.074164 -0.241550  0.054021 -1.356663 -0.744511
31034    36183.0  1.292040  0.537435 -0.906045  0.569620  0.514819 -0.675480
35267    38041.0 -0.713402  1.405427  1.307231  2.423319  0.103309  1.070906
258846  158850.0  0.028286  0.821887  0.284475 -0.586501  0.413510 -1.054221
134491   80831.0  1.513781 -1.030080  0.060288 -1.561056 -0.941979 -0.070830
49621    44137.0  0.619721 -2.376071  0.357566 -0.964897 -2.110271 -0.488130
275234  166437.0 -0.619418  0.822471 -0.818036  1.300766  1.836554 -0.649880
160909  113732.0 -0.999360  0.364624  0.654640 -0.302613  2.145747 -1.045892
102177   68079.0  1.099946  0.022106  0.271042  0.976475 -0.301424 -0.381163
188020  127788.0  0.008952  0.111853 -0.225614 -0.557647 -0.242147  0.089053
277509  167689.0 -0.195814  0.775087 -0.061407 -0.840261  0.364790 -0.580206
173264  121412.0  0.137599  0.944583 -0.573595 -0.757099  1.143641 -0.279081
...          ...       ...       ...       ...       ...       ...       ...
251891  155548.0  1.878230  1.325630 -2.333469  4.233151  1.355184 -0.853508
251904  155554.0 -1.040067  3.106703 -5.409027  3.109903 -0.887237 -2.497522
252124  155662.0 -1.928613  4.601506 -7.124053  5.716088  1.026579 -3.189073
252774  155965.0 -1.201398  4.864535 -8.328823  7.652399 -0.167445 -2.767695
254344  156685.0 -0.129778  0.141547 -0.894702 -0.457662  0.810608 -0.504723
254395  156710.0  0.202402  1.176270  0.346379  2.882138  1.407133 -0.504355
255403  157207.0  1.170756  2.501038 -4.986159  5.374160  0.997798 -1.259004
255556  157284.0 -0.242245  4.147186 -5.672349  6.493741  1.591168 -1.602523
258403  158638.0 -5.976119 -7.196980 -5.388316  5.104799  4.676533 -5.566870
261056  159844.0 -0.408111  3.132944 -3.098030  5.803893  0.890609 -0.501474
261473  160034.0 -2.349340  1.512604 -2.647497  1.753792  0.406328 -2.188494
261925  160243.0 -2.783865  1.596824 -2.084844  2.512986 -1.446749 -0.828496
262560  160537.0  0.567539  3.309385 -6.631268  6.394574 -0.054172 -2.396535
262826  160665.0 -0.417340  4.700055 -7.521767  7.671884  0.260821 -2.646693
263080  160791.0  2.132386  0.705608 -3.530759  0.514779  1.527175 -1.716268
263274  160870.0 -0.644278  5.002352 -8.252739  7.756915 -0.216267 -2.751496
263324  160895.0 -0.848290  2.719882 -6.199070  3.044437 -3.301910 -1.992117
263877  161154.0 -3.387601  3.977881 -6.978585  1.657766 -1.100500 -3.599487
268375  163181.0 -5.238808  0.623013 -5.784507  1.678889 -0.364432 -0.477295
272521  165132.0 -7.503926 -0.360628 -3.830952  2.486103  2.497367  1.332437
274382  165981.0 -5.766879 -8.402154  0.056543  6.950983  9.880564 -5.773192
274475  166028.0 -0.956390  2.361594 -3.171195  1.970759  0.474761 -1.902598
275992  166831.0 -2.027135 -1.131890 -1.135194  1.086963 -0.010547  0.423797
276071  166883.0  2.091900 -0.757459 -1.192258 -0.755458 -0.620324 -0.322077
276864  167338.0 -1.374424  2.793185 -4.346572  2.400731 -1.688433  0.111136
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7         V8        V9  ...       V20       V21       V22  \
214498 -0.284399  -0.211947  0.192514  ...  1.036037  0.707664  1.066778
46824  -0.858524   0.365723 -0.860695  ... -0.059793  0.046794  0.191504
85248  -0.654740  -0.808509 -0.881555  ... -1.773142  0.162701 -0.143771
95664   0.911122   0.615821 -1.182436  ... -0.103910 -0.125048 -0.442742
14540   0.435428   0.054402  0.094119  ... -0.186789  0.024123  0.220836
75526  -0.028195  -0.055905 -0.204120  ... -0.091531 -0.225237 -0.700154
20983   0.125318  -0.260510 -0.064082  ... -0.072156 -0.247963 -0.699585
158892  1.477558  -0.719594 -0.015652  ...  0.465433  0.492887  0.661144
98978  -0.049609   0.050085 -0.119814  ... -0.011247 -0.349397 -1.029105
210777 -0.728095  -0.108219 -0.032139  ... -0.106655  0.164916  0.487244
158808 -0.050809   0.125748  0.706033  ... -0.284957  0.327802  1.219275
243432  0.224469   0.268100 -1.086995  ... -0.315213 -0.332024 -0.829262
94620  -0.741665   1.140831 -3.325301  ... -0.069350 -0.439513 -1.301783
66036   1.584562   0.441496  0.453834  ...  0.698270  0.266004 -0.208050
236183  0.206896   0.707631 -0.066897  ...  0.294464  0.267961  0.343342
157613  0.153851  -0.197465  1.370202  ... -0.251347 -0.421889 -0.854198
243230  1.741768  -0.082562 -0.601833  ... -0.071950  0.547472  1.525733
30246   1.144847   0.740818  0.369087  ...  0.291764 -0.198622 -0.325971
236619 -0.574856  -0.196898  0.117259  ... -0.421864 -0.845427 -1.821374
31034   0.246614  -0.081672 -0.273091  ... -0.073441 -0.163986 -0.478165
35267  -0.301386   0.812398 -1.422561  ...  0.219933  0.200512  0.516604
258846  0.969398  -0.161170  0.007765  ... -0.064245 -0.257715 -0.577017
134491 -0.968532  -0.079822 -1.840210  ... -0.290693 -0.231404 -0.243088
49621  -0.587981  -0.168344 -1.812376  ...  0.492702 -0.063906 -0.759803
275234  1.963013  -0.438465 -1.168854  ...  0.574500  0.098205  0.291522
160909 -0.966374  -0.711181 -0.183697  ... -0.380689  1.128370  0.568971
102177  0.011340   0.020254 -0.044679  ... -0.060072  0.000448 -0.185053
188020 -0.714521  -2.603536  0.236170  ...  0.620735 -1.407089 -0.260083
277509  0.753872   0.125295  0.321385  ... -0.056250 -0.302256 -0.787633
173264  0.821144   0.093324 -0.200324  ...  0.007107 -0.325926 -0.844166
...          ...        ...       ...  ...       ...       ...       ...
251891  0.716025  -0.164910 -1.502345  ... -0.226108 -0.152131 -0.360736
251904 -2.073347   0.639818 -3.013331  ...  1.054390  0.773961  0.214868
252124 -2.261897   1.185096 -4.441942  ...  0.328796  0.602291 -0.541287
252774 -3.176421   1.623279 -4.367228  ...  0.597026  0.532320 -0.556913
254344  1.373588  -0.209476  0.208494  ...  0.399447 -0.032643 -0.246526
254395  1.438537  -0.395603 -1.555142  ... -0.206239  0.242560  0.841230
255403 -1.237689   0.358426 -2.612489  ...  0.227618  0.123145 -0.713201
255556 -0.950463   0.722903 -4.128505  ...  0.562030  0.249023 -0.480286
258403 -4.291180   0.876531 -1.075478  ...  3.136338  1.459369 -0.136262
261056 -0.440054   0.591828 -3.267693  ...  0.499568  0.098482 -0.538375
261473 -0.686935  -0.547984 -0.099528  ... -0.093421 -0.088519 -0.595178
261925 -0.732262  -0.203329 -0.347046  ... -0.515001  0.203563  0.293268
262560 -2.792489   0.514811 -3.541780  ...  0.555412  0.614221 -0.365047
262826 -2.854432   0.958783 -4.588536  ...  0.832035  0.622200 -0.437708
263080  1.132791  -0.574214  0.128904  ... -0.211167  0.163739  0.703910
263274 -3.358857   1.406268 -4.403852  ...  0.816558  0.587728 -0.605759
263324 -3.734902   1.520079 -2.548788  ...  0.319576  1.125229  0.805258
263877 -3.686651   1.942252 -3.065089  ... -0.004301  1.043587  0.262189
268375 -4.276132  -0.695173 -2.971644  ... -0.203270 -0.326140  1.509239
272521 -6.783964 -15.415385  0.465512  ... -0.475126 -6.389132  2.249964
274382 -5.748879   0.721743 -1.076274  ...  2.493224  0.880395 -0.130436
274475 -0.055178   0.277831 -1.745854  ...  0.190877  0.473211  0.719400
275992  3.790880  -1.155595 -0.063434  ...  0.033804 -0.315105  0.575520
276071 -1.082511   0.117200 -0.140927  ...  0.037438  0.288253  0.831939
276864 -0.922038  -2.149930 -2.027474  ...  0.650196 -0.870779  0.504849
279863 -0.882850   0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170   0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739   1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002   1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050  -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
214498 -0.436039  0.769297 -0.030186  0.024106 -0.093899  0.038912  525.00
46824   0.299998 -0.639175 -0.112026 -0.372801  0.085434  0.011683    6.41
85248   0.329086 -0.254146  0.279256 -0.006137 -0.493973  0.533954   57.50
95664   0.474038  0.364532 -0.270391 -0.623670  0.166097 -0.121757  141.00
14540   0.130776  0.393479 -0.281325 -0.473685  0.012610 -0.063104   16.73
75526   0.144795  0.488750  0.150520  0.065149 -0.028260  0.022215    1.98
20983   0.190147  0.888614  0.158495  0.060089 -0.019817  0.037102    1.98
158892 -0.514533  0.135380  0.494021  0.682348 -0.206478 -0.026702  398.40
98978  -0.096646 -1.437338  0.419601  0.184018 -0.028456  0.003075    0.64
210777  0.198644  0.599731 -0.066245 -0.180755 -0.023103 -0.055472    1.00
158808  0.051551 -0.527720  0.195976 -0.342456  0.055536 -0.060165    1.00
243432  0.404981 -1.284494 -0.498586 -0.248097  0.048143  0.007905   12.02
94620  -0.043762  0.945615  0.362410 -0.299586 -0.066611 -0.016316   31.99
66036   1.151451 -0.409131 -0.266660 -0.261209 -0.238761 -0.014212  469.81
236183  0.406721 -0.984052 -0.179999 -0.955373  0.336323 -0.097173  238.47
157613  0.227522 -0.621212 -0.084722 -0.934580 -0.000948 -0.034688    9.99
243230  0.238003  0.793955 -1.105472  0.356395  0.335332  0.332662  103.19
30246  -0.097985  1.032732  0.498425  0.235193  0.110361 -0.168744  332.35
236619  0.543674  0.429612 -0.746921  0.069806 -0.020757 -0.023466   91.17
31034  -0.190393 -0.626401  0.629353  0.404900 -0.039777  0.022931    0.76
35267  -0.307775 -1.006444 -0.050429  0.395305  0.262549  0.105712   10.62
258846  0.083295 -0.029817 -0.515631  0.144581  0.247593  0.096311    3.59
134491 -0.053212 -0.780558  0.432672 -0.126711  0.045295  0.011674   24.88
49621  -0.123160  0.363000 -0.141028 -0.445307 -0.019940  0.103198  435.70
275234 -0.099331 -0.598198  0.374619 -0.364733 -0.045905 -0.015786  158.00
160909 -2.225172  0.816641 -0.103686 -0.347935  0.323283  0.164452    1.00
102177 -0.112191 -0.025935  0.502232 -0.439129  0.000914  0.020280   62.48
188020 -0.214359 -0.366580  1.082304  0.005924 -0.108429  0.077201  122.04
277509  0.046778 -0.576526 -0.493939  0.164127  0.336008  0.134284   13.99
173264  0.029558  0.077116 -0.410414  0.123705  0.215456  0.068504    0.89
...          ...       ...       ...       ...       ...       ...     ...
251891  0.043414 -0.242380  0.171098 -0.002601 -0.026667  0.005238    7.06
251904 -0.184233 -0.284091  0.493467  0.732329  0.675067  0.337076   94.82
252124 -0.354639 -0.701492 -0.030973  0.034070  0.573393  0.294686    0.77
252774  0.192444 -0.698588  0.025003  0.514968  0.378105 -0.053133    0.77
254344  0.484108  0.359637 -0.435972 -0.248480  0.021527  0.109192  187.11
254395 -0.370157 -0.026012  0.491954  0.234576 -0.279788 -0.331933    7.59
255403 -0.080868 -0.964310  0.338568  0.068630  0.481588  0.268226    4.97
255556 -0.286080 -1.153575 -0.035571  0.559628  0.409446  0.221048    0.77
258403  0.848177 -0.269916 -1.095060 -0.710905  0.565846 -1.034107  296.00
261056 -0.217989 -1.042657  0.314389  0.543244  0.233851  0.119603   45.51
261473  0.258148  0.061901 -0.354180 -1.152671 -0.736073  0.733703    4.90
261925  0.199568  0.146868  0.163602 -0.624085 -1.333100  0.428634  156.00
262560 -0.180409 -0.523271  0.645054  0.246466  0.902675  0.473571    4.69
262826 -0.090358 -0.742802 -0.312361  0.502575  0.821390  0.372379    0.77
263080 -0.245076  0.460049  0.920281 -0.216586 -0.026219 -0.025001    1.00
263274  0.033746 -0.756170 -0.008172  0.532772  0.663970  0.192067    0.77
263324  0.199119  0.035206  0.012159  0.601658  0.137468 -0.171397  127.14
263877 -0.479224 -0.326638 -0.156939  0.113807  0.354124  0.287592    0.38
268375 -0.215966 -0.245727  0.893041  0.865758  0.854657 -0.964482   39.98
272521  1.670508  0.140450  0.162147  1.207731  1.268958  0.097538   12.31
274382  2.241471  0.665346 -1.890041 -0.120803  0.073269  0.583799    0.00
274475  0.122458 -0.255650 -0.619259 -0.484280  0.683535  0.443299   39.90
275992  0.490842  0.756502 -0.142685 -0.602777  0.508712 -0.091646  634.30
276071  0.142007  0.592615 -0.196143 -0.136676  0.020182 -0.015470   19.95
276864  0.137994  0.368275  0.103137 -0.414209  0.454982  0.096711  349.08
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [21]:
print(Y)

214498    0
46824     0
85248     0
95664     0
14540     0
75526     0
20983     0
158892    0
98978     0
210777    0
158808    0
243432    0
94620     0
66036     0
236183    0
157613    0
243230    0
30246     0
236619    0
31034     0
35267     0
258846    0
134491    0
49621     0
275234    0
160909    0
102177    0
188020    0
277509    0
173264    0
         ..
251891    1
251904    1
252124    1
252774    1
254344    1
254395    1
255403    1
255556    1
258403    1
261056    1
261473    1
261925    1
262560    1
262826    1
263080    1
263274    1
263324    1
263877    1
268375    1
272521    1
274382    1
274475    1
275992    1
276071    1
276864    1
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [23]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [24]:
model = LogisticRegression()

In [25]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [27]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9440914866581956

In [28]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [29]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9289340101522843